clamsproject/clams-python

clams/source/__init__.py
Code was trying to iterate over `None` from the default parameters. Method now replaces the value of `common_documents_json` with `[]` if it is `None`, and replaces the value of `common_metadata_json` with `dict()` if it is `None`.
Default `metadata` in `self.mmif_start` now includes `"mmif": f"http://mmif.clams.ai/{__specver__}"`, which will be overwritten by any user-defined value for `metadata["mmif"]`.
=> Bugfix with clams.source.PipelineSource.__init__()

clams/__init__.py, clams/source/__init__.py, clams/utils/__init__.py, setup.py
Arguments to `clams source` should be colon-joined pairs of MIME types and filepaths. The output will be a MMIF file containing a document for each of those filepaths, with the appropriate `@type` and MIME type, printed to the standard output.
Top-level MIME types should be one of `audio`, `video`, `text`, and `image`. Subtypes, such as `video/mpeg`, are permitted.
For example:
```
$ clams source video/mpeg:/var/archive/video-002.mp4 text:/var/archive/transcript-002.txt
{
"metadata": {
"mmif": "http://mmif.clams.ai/0.2.1"
},
"documents": [
{
"@type": "http://mmif.clams.ai/0.2.1/vocabulary/VideoDocument",
"properties": {
"mime": "video/mpeg",
"location": "/var/archive/video-002.mp4",
"id": "d1"
}
},
{
"@type": "http://mmif.clams.ai/0.2.1/vocabulary/TextDocument",
"properties": {
"mime": …
```
=> Add 'clams' CLI utility and implement 'clams source' action

clams/restify/__init__.py, tests/test_clamsapp.py
=> Error responses now use code 500 

.github/workflows/codecov.yml, .github/workflows/publish.yml, .gitignore, Makefile, clams/app/__init__.py, clams/appmetadata/__init__.py, clams/source/__init__.py, documentation/appdirectory.rst, documentation/autodoc/clams.app.rst, documentation/autodoc/clams.appmetadata.rst, documentation/conf.py, documentation/index.rst, documentation/introduction.rst, documentation/modules.rst, documentation/tutorial.rst, requirements.dev, requirements.txt, setup.py, tests/test_clamsapp.py
This PR addresses #49, #52, and clamsproject/clams-apps#18 . Concretely, app metadata is defined as python objects (in `clams/appmetadata/__init__.py`) and *exported* as a JSON file while building documentation ([here](https://github.com/clamsproject/clams-python/compare/develop...49-metadata-schema?expand=1#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R46)). Generated JSON schema file has `$comment` field where developers can store the version of SDK used. At the moment, I don't see a point to keep a separate versioning for the schema, but if you use the same version string between the python SDK and app metadata schema, we need to carefully think through the compatibility issues when app metadata scheme is updated in the public branch. For now, input and output …
=> Adding appmetadata schema

clams/appmetadata/__init__.py
=> making typing.Literal work on py>3.6

clams/app/__init__.py, clams/appmetadata/__init__.py, clams/restify/__init__.py, requirements.txt, tests/test_clamsapp.py
This release contains various fixes and improvements. 
* updated mmif-python to 0.4.4
* (added) C`lamsApp.get_configuration` will convert runtime parameters into actual runtime configuration that the app uses. This will help signing view.
* (fixed) Crash when `sign_view` with non-string parameter values
* (changed) MMIF with error is always prettified when returned as HTTP response
* (fixed) Adding duplicate input/output should not be allowed
* (changed) `AppMetadata.add_parameter` now has a proper signature for IDE hints
=> releasing 0.4.3

requirements.txt
This addresses #94 only by pinning to an older version of `markupsafe`. In the long term, we should consider updating flask to flask2.
=> pinned problematic dependency, updated flask 1.1

.github/workflows/codecov.yml, .github/workflows/dockerhub.yml, .github/workflows/publish.yml, clams/appmetadata/__init__.py, requirements.dev, requirements.txt, setup.py
This PR includes updates on
1. minimum python requirements (also see https://github.com/clamsproject/mmif-python/issues/191) 
2. flask version (1 -> 2) (see #94)
3. "uncapping" other dependency versions. (see #89)
Using a new major version of flask needs more testing, which I'm working on.
=> updating dependency versions

clams/app/__init__.py, tests/test_clamsapp.py
=> metadata returned by GET calls now includes information about "universal" parameters

.github/workflows/codecov.yml, clams/app/__init__.py, clams/appmetadata/__init__.py, tests/test_clamsapp.py
This PR closes #114. 
A few notes; 
* `app_version` value is generated using `git describe` first, and then using `$CLAMS_APP_VERSION` environment variable, then falls back to `unresolvable`. `git describe` comes first to ensure the proper versions are inferred in case where multiple apps running all natively (not via containers). (d0006dc)
* ~~The generation is done via pydantic default_factory, which won't prevent users from manually setting a value. I made it clearer in the documentation that this field (along with some others) is automatically filled, but existing apps need to be updated to "unset" app_versions.~~ (no longer the case after f8c6965)
* The generated version number is then automatically appended to the `identifier`. It means all existing apps should also be updated if …
=> auto generate `app_version` value

clams/appmetadata/__init__.py, clams/develop/templates/app/metadata.py, clams/develop/templates/github/workflows/container.yml, clams/develop/templates/github/workflows/publish.yml
This PR updates the app *publish* actions workflow (formerly `container` workflow) with integration with the prototype app-directory (https://github.com/clamsproject/apps/issues/15) . 
Closes #134 .
=> app directory integration

clams/appmetadata/__init__.py, tests/test_clamsapp.py
=> fixed version generation was not working when `git` cmd not found

requirements.txt
This release includes a bugfix and update to the latest mmif-python 
* now based on `mmif-python==1.0.7`
* fixed some runtime parameters' default values not correctly casted (#173 )
=> releasing 1.0.7

clams/appmetadata/__init__.py, tests/test_clamsapp.py
=> default values for `mutlivalued=True` params now must be lists

requirements.txt
Minor release to update the `mmif-python` dependency to the latest.
* now based on `mmif-python==1.0.13` including a hotfix for a wrong field name in MMIF serialization.
=> releasing 1.1.6

clams/app/__init__.py, tests/test_clamsapp.py
fixes #209, also FINALLY breaks backward compatibility to `clams-python==1.0.x`
=> fixing raw params (`#RAW#`) in `appConfiguration`

clams/app/__init__.py, clams/appmetadata/__init__.py, requirements.txt, tests/test_clamsapp.py
This is a minor release that brings improved portability of `clams source` command but also breaks some backward compatibility. If your app is based on clams-python 1.0.x or 1.1.x, please read the changelog carefully. 
- `clams source` command now work on Windows shell. The paths still, though, have to be POSIX path. We have no plan to support Windows path for `file://` URI in MMIF at the moment. 
- `ClamsApp.sign_view` method now expect the runtime parameters (dict of string to lists of values) as a second argument. Previously the second argument was optional, which is no more. CLAMS app developers who were calling this method in `_annotate()` method must directly pass down the runtime parameters from `_annotate()` argument.
=> releasing 1.2.0

clams/app/__init__.py, clams/develop/templates/app/app.py.template
=> fixed multivalued parameter values were not correctly recorded in output MMIF

clams/app/__init__.py, clams/appmetadata/__init__.py, clams/develop/__init__.py, clams/develop/templates/app/app.py.template, clams/develop/templates/app/cli.py.template, clams/mmif_utils/rewind.py, clams/restify/__init__.py, documentation/clamsapp.md
This PR addresses #198 , by adding a "cli.py" template to the clams SDK. This script iterates over the "parameters" in a new app's metadata and parses them into argparse arguments. From here, it collects those arguments and stdin, runs `app._annotate()` , and produces the result to stdout
Generally, I think the areas that I'm least sure about:
- Safer / more idiomatic access to stdin / stdout
- I didn't add the template to any scripts, if that's something needed
=> adding `cli.py` for command line app use

clams/app/__init__.py
=> when creating an "error view", only "raw" parameters are recodred in the view metadata

clams/app/__init__.py, clams/develop/templates/app/Containerfile.template, container/opencv4.containerfile, requirements.txt, tests/test_clamsapp.py
Patch release to update mmif SDK version, and minor improvements
- `clams source --help` will display formatting guidelines for docloc plugins, if provided by the plugin developer (https://github.com/clamsproject/clams-python/issues/235)
- now based on `mmif-python` 1.0.18
- bug fix "raw" runtime parameters weren't properly recorded when an app fails to refine the parameters (https://github.com/clamsproject/clams-python/issues/232)
=> releasing 1.2.6

clams/app/__init__.py, tests/test_clamsapp.py
addresses #236 
Sample output; 
``` json 
"views": [                                                                                                                                 
{
"id": "v_0",
"metadata": {
"runtime": {
"runningTime": "0:00:05.466913",    # runningTime=True
"architecture": "x86_64",           # hwFetch=True
"cuda": [
"NVIDIA RTX A6000 (49140 MiB)",
"NVIDIA RTX A6000 (49140 MiB)",
"NVIDIA RTX A6000 (49140 MiB)",
"NVIDIA RTX A6000 (49140 MiB)"
]
},
"timestamp": "2024-07-05T21:00:07.408801",
"app": "http://apps.clams.ai/swt-detection/v5.1-9-g6b12498",
"contains": {
"http://mmif.clams.ai/vocabulary/TimePoint/v4": {
...
},
"http://mmif.clams.ai/vocabulary/TimeFrame/v5": {
...
},
"http://mmif.clams.ai/vocabulary/Annotation/v5": {
...
}
},
"parameters": {
"pretty": "", …
```
=> added runningtime and hwinfo recorder (as universal params)

clams/develop/templates/app/Containerfile.template, container/opencv4.containerfile, documentation/appmetadata.rst, documentation/autodoc/clams.appmetadata.rst, requirements.txt
This version added two universal runtime parameters that make some aspects of the runtime environment are recorded in the views' metadata. 
- `hwFetch` universal parameter will record CPU architecture and CUDA devices in `view.metadata.appRunningHardware` 
- `runningTime` universal parameter will record app's running time in `view.metadata.appRunningTime`
- See https://github.com/clamsproject/clams-python/issues/236 for rationale behind
=> releasing 1.3.0

Makefile, clams/develop/templates/app/metadata.py.template
=> fixing metadata generation is relying on a fixed path of code
