- clams/restify/__init__.py
- clams/vocab/__init__.py
> Scene detect

- clams/serialize/__init__.py
addressing a big TODO item in serialization module.
> added deserialization code for MMIF objects

- clams/serialize/__init__.py
Reverts clamsproject/clams-python-sdk#9 as #9 contains some breaking changes. Will open a new PR when those changes are fixed to be not "breaking".
> Revert "added deserialization code for MMIF objects"

- clams/vocab/__init__.py
lastest non-merging commit (7b745b7a5b087906c14cd555678cc43a1b179a78) on current `shot_detect` branch is conflicting with the changes from #6. This PR is merging the next to latest commit in the `shot_detect` branch into develop. 
@kelleyl please review the above statement of mine. If it's correct, please go ahead and merge this, and delete current `shot_detect` branch.
> changing scene to shot

- clams/vocab/__init__.py
Trivial PR to add vocab items. @kelleyl please add more commits if you need specific `at_type` as well for page segments.
> adding image to vocab, media type

- clams/__init__.py
- clams/serve/__init__.py
- clams/source/__init__.py
- clams/utils/__init__.py
- setup.py
- tests/test_clamsapp.py
0.1.3 includes; 
* `clams` CLI
* `clams source` command
* replacement of `appmetadata` with `setupmetadata` in `ClamsApp` ABC
> releasing 0.1.3

- .gitignore
- clams/__init__.py
- clams/source/__init__.py
- setup.py
> bugfixes and `__version__`

- clams/restify/__init__.py
- clams/serve/__init__.py
Regarding #28, this PR implements a minimal error handling on HTTP side and adding a common file check method
> a tiny bit better error handling

- clams/app/__init__.py
- clams/restify/__init__.py
- documentation/introduction.rst
- documentation/tutorial.rst
- tests/test_clamsapp.py
This PR contains some breaking changes. See #29 for discussions.
> initial implementation of parameterized `annotate`

- clams/app/__init__.py
- tests/test_clamsapp.py
> 40 sign view

- clams/app/__init__.py
- clams/restify/__init__.py
- tests/test_clamsapp.py
This PR addresses #36. There is a pending PR https://github.com/clamsproject/mmif-python/pull/159 to address the related issue in the lower level so the code written in this PR will likely need to be re-written with that PR.
> adding error handling code for restifier

- clams/app/__init__.py
- requirements.txt
- tests/test_clamsapp.py
> updating error handling with a newer version of mmif-python

- clams/app/__init__.py
- clams/restify/__init__.py
- requirements.txt
- tests/test_clamsapp.py
This release includes small updates of error handling matching updates on mmif-python side.
> releasing 0.2.4

- clams/restify/__init__.py
- documentation/introduction.rst
> implementing production server

- .github/workflows/publish.yml
- clams/app/__init__.py
- clams/appmetadata/__init__.py
- documentation/conf.py
- documentation/index.rst
- documentation/introduction.rst
- documentation/target-versions.csv
- documentation/target-versions.rst
- requirements.txt
- tests/test_clamsapp.py
> adding compatibility check in `annotate()`

- clams/__init__.py
- clams/source/__init__.py
> refactoring and fixing bugs in CLI

- docker/ffmpeg-tf2.dockerfile
- docker/ffmpeg-torch.dockerfile
- docker/ffmpeg.dockerfile
- docker/opencv4-tf2.dockerfile
- docker/opencv4-torch.dockerfile
- docker/tf2.dockerfile
- docker/torch.dockerfile
- requirements.txt
This release includes bug fixes from mmif-python package, loosened ML library versions in docker images.
> releasing 0.4.4

- clams/app/__init__.py
- clams/appmetadata/__init__.py
- tests/test_clamsapp.py
This PR updates `AppMetadata` schema as discussed in #80 and #83. 
Closes #80. 
Closes #83.
> updateing AppMetadata scheme

- clams/restify/__init__.py
> fixing bug that removed any non-boolean parameters

- clams/appmetadata/__init__.py
- tests/test_clamsapp.py
This PR adds two more fields to app metadata, as discussed in #79. 
Closes #79.
> 79 dependency in appmetadata

- Makefile
- requirements.txt
> fixing dev version generation 

- clams/restify/__init__.py
- tests/test_clamsapp.py
This release contains fixes in the development pipelines (#97 ) and dependency ( #95).
> releasing 0.5.1

- clams/app/__init__.py
- clams/source/__init__.py
- requirements.txt
- tests/test_clamsapp.py
> removed usage of freezing methods in mmif objects

- clams/app/__init__.py
- clams/appmetadata/__init__.py
- clams/restify/__init__.py
- requirements.txt
- tests/test_clamsapp.py
Fixing #101 by changing default behavior given an undefined runtime parameter.
> adding handling of warnings, undefined parameters to warnings

- Makefile
- clams/app/__init__.py
- clams/appmetadata/__init__.py
- clams/restify/__init__.py
- tests/test_clamsapp.py
> fixing "falsy" default values of runtime params

- clams/__init__.py
- clams/source/__init__.py
> added more structured help messages for subcommands

- .pytype.cfg
- Makefile
- clams/__init__.py
- clams/develop/__init__.py
- clams/develop/templates/app/.gitignore
- clams/develop/templates/app/CLAMS-generic-readme.md
- clams/develop/templates/app/Containerfile
- clams/develop/templates/app/LICENSE
- clams/develop/templates/app/README.md
- clams/develop/templates/app/app.py
- clams/develop/templates/app/requirements.txt
- clams/develop/templates/github/workflows/container.yml
- clams/develop/templates/github/workflows/issue-assign.yml
- clams/develop/templates/github/workflows/issue-close.yml
closes #119 .
The current scaffolding github repo should be shut down when a clams-python with this PR is release.
> add CLI to make a local copy of app scaffolding

- .github/workflows/container.yml
- container/ffmpeg-torch2.containerfile
- container/opencv4-torch2.containerfile
- container/torch2.containerfile
fixes #126, also adds more images with pytorch2 (#30)
> adding support for arm64 images

- clams/app/__init__.py
- clams/develop/templates/app/app.py
- clams/develop/templates/app/metadata.py
- clams/develop/templates/github/workflows/issue-apps-project.yml
- tests/metadata.py
- tests/test_clamsapp.py
> adding support for `metadata.py` and `metadata.json` 

- clams/app/__init__.py
- requirements.txt
- tests/test_clamsapp.py
> removing legacy style at_type version checking

- .github/workflows/issue-infra-project.yml
- clams/develop/templates/app/.dockerignore
- clams/develop/templates/app/README.md
- clams/develop/templates/app/app.py
- clams/develop/templates/app/metadata.py
- setup.py
> fixed sdist to include app template files, minor updates to the template

- clams/develop/templates/app/Containerfile
- clams/develop/templates/github/workflows/container.yml
This PR fixes (only partially) #134.
> 134 update app container action

- requirements.dev
> put lower bound to setuptools to support all feature we used in setup.py

- requirements.txt
This release includes all the `clamsproject`-specific GHA workflow files in the PyPI distribution. 
* fixed GHA workflow files were missing in the sdist uploaded to PyPI (#143)
> releasing 0.6.2

- clams/app/__init__.py
> fixed all runtime parameters were casted to str

- clams/app/__init__.py
- clams/develop/templates/app/README.md.template
- clams/develop/templates/app/metadata.py.template
- container/opencv4.containerfile
- requirements.txt
- tests/test_clamsapp.py
> adding a check for `choices`-enabled runtime parameters

- requirements.txt
Minor release to update `mmif-python` version 
* updated to `mmif-python==1.0.5`
> releasing 1.0.5

- requirements.txt
Minor release to update `mmif-python` version 
* updated to `mmif-python==1.0.5`
> releasing 1.0.6

- clams/appmetadata/__init__.py
- tests/test_clamsapp.py
fixes https://github.com/clamsproject/clams-python/issues/173.
> fixing rumtime parameter default value casting bug

- clams/app/__init__.py
- clams/develop/templates/app/README.md.template
- clams/develop/templates/app/app.py.template
- requirements.txt
Minor release to update `mmif-python` version 
* updated to `mmif-python==1.0.8`
* enabled a python logger for clams-apps as `self.logger`
> releasing 1.0.8

- clams/develop/templates/app/README.md.template
- clams/develop/templates/app/app.py.template
- clams/develop/templates/app/metadata.py.template
Minor release to update small issues in the app develop template. 
* `metadata.py` from the template now includes *universal* parameters when printing out the app metadata.
> releasing 1.0.10

- clams/app/__init__.py
- tests/test_clamsapp.py
> added validation step in `annotate()` before return the MMIF JSON str

- clams/app/__init__.py
- clams/develop/templates/app/README.md.template
- clams/develop/templates/app/app.py.template
- clams/restify/__init__.py
- tests/test_clamsapp.py
> sign_view now uses "raw" input parameters, if available.

- clams/restify/__init__.py
> added logging-to-stdout for production mode restifier

- container/Containerfile
- container/ffmpeg-tf2.containerfile
- container/ffmpeg-torch.containerfile
- container/ffmpeg-torch2.containerfile
- container/ffmpeg.containerfile
- container/opencv4-tf2.containerfile
- container/opencv4-torch.containerfile
- container/opencv4-torch2.containerfile
- container/opencv4.containerfile
- container/tf2.containerfile
- container/torch.containerfile
- container/torch2.containerfile
> no pip cache in container images to reduce image sizes

- clams/appmetadata/__init__.py
> fixed `git describe` error when whitespace in git path

- clams/app/__init__.py
- clams/mmif_utils/rewind.py
- requirements.txt
- tests/test_clamsapp.py
This release updates to the latest MMIF and `mmif-python`
* Now based on `mmif-python` 1.0.9 and MMIF 1.0.1
> releasing 1.1.2

- clams/appmetadata/__init__.py
- requirements.txt
This is a minor release to catch up new version of MMIF and `mmif-python`. 
* updated to latest mmif-python (and MMIF 1.0.2)
* small updates in API documentation regarding I/O spec in app metadata
> releasing 1.1.3

- clams/appmetadata/__init__.py
- tests/test_clamsapp.py
> added methods that allows additional type-level descriptions

- clams/app/__init__.py
- clams/appmetadata/__init__.py
- clams/restify/__init__.py
- requirements.txt
- tests/test_clamsapp.py
> signing a view now auto-record `appConfiguration` 

- clams/app/__init__.py
- clams/appmetadata/__init__.py
- tests/test_clamsapp.py
Hot-fix to fix some compatibility issues in the app develop template 
* reverted some changes from 3ed54b3 due to broken backward compatibility
> releasing 1.1.5

- clams/app/__init__.py
- clams/restify/__init__.py
- tests/test_clamsapp.py
> bugfix in parameter passing

- clams/app/__init__.py
- tests/test_clamsapp.py
> additional fix for parameter refinement

- clams/develop/templates/app/Containerfile.template
- container/Containerfile
- container/opencv4.containerfile
- documentation/clamsapp.md
> based image updated to debian12

- clams/develop/__init__.py
- clams/develop/templates/app/Containerfile.template
- clams/develop/templates/app/README.md.template
- clams/develop/templates/app/app.py.template
- clams/develop/templates/app/cli.py.template
- clams/develop/templates/app/metadata.py.template
- documentation/tutorial.md
- requirements.txt
Patches bug in `clams develop` command and updated in documentation and `mmif-python` version 
* fixed `clams develop` command not working to start a new app from scratch
* updated `mmif-python` version to 1.0.16
* updated app development documentation
> releasing 1.2.4

- clams/app/__init__.py
- clams/develop/templates/app/Containerfile.template
- requirements.txt
- tests/test_clamsapp.py
Patch release to fix an error in app cookie cutter, also updated to the latest MMIF and mmif-python. 
- updated `mmif-python` to 1.0.17
- fixed `Containerfile` from the app cookie cutter wasn't building an image due to an error
> releasing 1.2.5

- clams/mmif_utils/source.py
> updated `clams source` command
